- 👋 Hi, I’m @FenixMeer!
- 👀 I’m interested in coding, gaming, and soccer.
- 🌱 I’m currently learning the Java programming language.
- 💞️ I’m looking to collaborate on easy coding projects.
- 📫 How to reach me: I'm on Scratch at: scratch.mit.edu/users/FenixMeer.
